name: Custom Default Settings Plugin Request

on:
  issues:
    types: [labeled, edited]

jobs:
  discord-webhook:
    runs-on: ubuntu-18.04
    steps:
      - if: contains(github.event.issue.labels.*.name, 'Custom Default Settings Plugin Request')
        name: Discord Webhook
        env:
          ISSUE_BODY: '${{github.event.issue.body}}'
        run: |
          curl \
            --fail \
            -H "Content-Type: application/json" \
            --data "{\"embeds\":[{\"author\":{\"name\":\"${{github.event.issue.user.login}}\",\"url\":\"${{github.event.issue.user.html_url}}\",\"icon_url\":\"${{github.event.issue.user.avatar_url}}\"},\"title\":\"${{github.event.issue.title}} (#${{github.event.issue.number}})\",\"description\":\"[Issue](https://github.com/vvanelslande/vvctre/issues/${{github.event.issue.number}})\n\nAction: ${{github.event.action}}\n\nBody:\n\`\`\`\n$(printf "$ISSUE_BODY" | sed -z 's/\r\n/\\n/g')\`\`\`\"}]}" \
            ${{secrets.CUSTOM_DEFAULT_SETTINGS_PLUGIN_REQUEST_LOGS}} \
            || curl \
              --fail \
              -H "Content-Type: application/json" \
              --data "{\"embeds\":[{\"author\":{\"name\":\"${{github.event.issue.user.login}}\",\"url\":\"${{github.event.issue.user.html_url}}\",\"icon_url\":\"${{github.event.issue.user.avatar_url}}\"},\"title\":\"${{github.event.issue.title}} (#${{github.event.issue.number}})\",\"description\":\"[Issue](https://github.com/vvanelslande/vvctre/issues/${{github.event.issue.number}})\n\nAction: ${{github.event.action}}\nBody: See issue (length is ${#ISSUE_BODY})\"}]}" \
              ${{secrets.CUSTOM_DEFAULT_SETTINGS_PLUGIN_REQUEST_LOGS}}
  before-making-plugin:
    if: contains(github.event.issue.labels.*.name, 'Custom Default Settings Plugin Request')
    runs-on: ubuntu-18.04
    needs: discord-webhook
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14.7.0'
      - uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/.github/scripts/custom-default-settings-plugin-request-before-making-plugin.js`)
            script(github, context)
  make-plugin:
    if: contains(github.event.issue.labels.*.name, 'Custom Default Settings Plugin Request')
    runs-on: ${{matrix.os}}
    needs: before-making-plugin
    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04]
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '>=14.9.0'
      - name: Script
        shell: bash
        working-directory: ${{github.workspace}}
        env:
          ISSUE_BODY: ${{github.event.issue.body}}
        run: |
          node .github/scripts/custom-default-settings-plugin-request-make-plugin.js

          if [ "$RUNNER_OS" == "Windows" ]; then
            cl.exe //LD //Fe:settings.dll plugin.c
          else
            gcc plugin.c -shared -o settings.so
          fi

          if [ "$RUNNER_OS" == "Windows" ]; then
            7z a vvctre-plugin-settings-${{runner.os}}.7z settings.dll plugin.c license.txt
          else
            7z a vvctre-plugin-settings-${{runner.os}}.7z settings.so plugin.c license.txt
          fi

          export FILE_URL=$(curl ${{secrets.ISSUE_BOT_FILES}} -s -F "file=@vvctre-plugin-settings-${{runner.os}}.7z" | jq -r .attachments[0].url)
          echo "FILE_URL=$FILE_URL" >> $GITHUB_ENV
      - uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{github.event.issue.number}}
          body: '[vvctre-plugin-settings-${{runner.os}}.7z](${{env.FILE_URL}})'
      - if: failure()
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{github.event.issue.number}}
          body: 'Error: https://github.com/vvanelslande/vvctre/actions/runs/${{github.run_id}}'
