name: Custom Default Settings Plugin Request

on:
  issues:
    types: [labeled, edited]

jobs:
  build:
    if: contains(github.event.issue.labels.*.name, 'Custom Default Settings Plugin Request')
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04]
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14.7.0"
      - name: Script
        shell: bash
        working-directory: ${{github.workspace}}
        env:
          ISSUE_BODY: ${{github.event.issue.body}}
        run: |
          node .github/scripts/custom-default-settings-plugin-request.js

          if [ "$RUNNER_OS" == "Windows" ]; then
            cl.exe //LD //Fe:settings.dll plugin.c
          else
            gcc plugin.c -shared -o settings.so
          fi

          if [ "$RUNNER_OS" == "Windows" ]; then
            7z a vvctre-plugin-settings-${{runner.os}}.7z settings.dll plugin.c license.txt
          else
            7z a vvctre-plugin-settings-${{runner.os}}.7z settings.so plugin.c license.txt
          fi

          export FILE_URL=$(curl ${{secrets.ISSUE_BOT_FILES}} -s -F "file=@vvctre-plugin-settings-${{runner.os}}.7z" -F "payload_json={\"content\":\"Issue: [${{github.event.issue.number}}](<https://github.com/vvanelslande/vvctre/issues/${{github.event.issue.number}}>)\nRequested By: [${{github.event.issue.user.login}}](<https://github.com/${{github.event.issue.user.login}}>)\nAction: ${{github.event.action}}\"}" | jq -r .attachments[0].url)
          echo ::set-env name=FILE_URL::$FILE_URL
      - uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{github.event.issue.number}}
          body: "[vvctre-plugin-settings-${{runner.os}}.7z](${{env.FILE_URL}})"
      - if: failure()
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{github.event.issue.number}}
          body: "Build Error: https://github.com/vvanelslande/vvctre/actions/runs/${{github.run_id}}"
  remove-useless-lines:
    if: contains(github.event.issue.labels.*.name, 'Custom Default Settings Plugin Request')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14.7.0"
      - uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/.github/scripts/custom-default-settings-plugin-request-remove-useless-lines.js`)
            script(github, context)
