name: Window Size Plugin Request

on:
  issues:
    types: [labeled, edited]

jobs:
  make-plugin:
    if: contains(github.event.issue.labels.*.name, 'Window Size Plugin Request')
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04]
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14.5.0'
      - name: Script
        shell: bash
        working-directory: ${{github.workspace}}
        env:
          ISSUE_BODY: ${{github.event.issue.body}}
        run: |
          node .github/scripts/window-size-plugin-request.js

          if [ "$RUNNER_OS" == "Windows" ]; then
            cl.exe //LD //Fe:window-size.dll plugin.c
          else
            gcc plugin.c -shared -o window-size.so
          fi

          mkdir zip

          if [ "$RUNNER_OS" == "Windows" ]; then
            mv window-size.dll plugin.c license.txt zip/
          else
            mv window-size.so plugin.c license.txt zip/
          fi
      - uses: actions/upload-artifact@v2
        with:
          name: vvctre-plugin-window-size-${{runner.os}}
          path: zip
  success:
    runs-on: ubuntu-18.04
    needs: make-plugin
    steps:
      - uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{github.event.issue.number}}
          body: |
            You can download your plugin from Artifacts from https://github.com/vvanelslande/vvctre/actions/runs/${{github.run_id}}
            The files are deleted after 30 days. You can rename the issue or edit it to rebuild the plugin.
  failure:
    if: failure()
    runs-on: ubuntu-18.04
    needs: make-plugin
    steps:
      - uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{github.event.issue.number}}
          body: |
            Failed to make the plugin.
            You can see the logs from https://github.com/vvanelslande/vvctre/actions/runs/${{github.run_id}}.
